version: "3.8"

services:
  datamonkey:
    image: ${DATAMONKEY_IMAGE:-service-datamonkey:latest}
    build:
      context: .
      dockerfile: Dockerfile
    hostname: service-datamonkey
    container_name: service-datamonkey
    volumes:
      - user_data:/data/uploads
      - tracker_data:/data/stores
      - output_data:/data/output
      # Mount JWT key for REST mode
      - ${JWT_KEY_VOLUME:-}
    expose: 
      - 9300
    ports: 
      - 9300:9300
    environment:
      # Common environment variables
      - DATASET_TRACKER_TYPE=${DATASET_TRACKER_TYPE:-SQLiteDatasetTracker}
      - DATASET_LOCATION=${DATASET_LOCATION:-/data/uploads}
      - DATASET_TRACKER_DB_PATH=${DATASET_TRACKER_DB_PATH:-/data/stores/datasets.db}
      - JOB_TRACKER_TYPE=${JOB_TRACKER_TYPE:-SQLiteJobTracker}
      - JOB_TRACKER_LOCATION=${JOB_TRACKER_LOCATION:-/data/stores}
      - JOB_TRACKER_DB_PATH=${JOB_TRACKER_DB_PATH:-/data/stores/jobs.db}
      - SLURM_INTERFACE=${SLURM_INTERFACE:-rest}
      - SLURM_QUEUE_NAME=${SLURM_QUEUE_NAME:-normal}
      - SERVICE_DATAMONKEY_PORT=${SERVICE_DATAMONKEY_PORT:-9300}
      - HYPHY_PATH=${HYPHY_PATH:-hyphy}
      - HYPHY_BASE_PATH=${HYPHY_BASE_PATH:-/data/output}
      # REST mode variables
      - SLURM_REST_URL=${SLURM_REST_URL:-http://c2:9200}
      - SLURM_REST_API_PATH=${SLURM_REST_API_PATH:-/slurmdb/v0.0.37}
      - SLURM_REST_SUBMIT_API_PATH=${SLURM_REST_SUBMIT_API_PATH:-/slurm/v0.0.37}
      # CLI mode variables
      - SLURM_CLI_HOST=${SLURM_CLI_HOST:-c2}
      - SLURM_CLI_USER=${SLURM_CLI_USER:-root}
      - SLURM_CLI_PASSWORD=${SLURM_CLI_PASSWORD:-root}
      - SLURM_CLI_PORT=${SLURM_CLI_PORT:-22}
      # Scheduler type is set based on SLURM_INTERFACE
      - SCHEDULER_TYPE=${SCHEDULER_TYPE:-${SLURM_INTERFACE:-rest}RestScheduler}
      # JWT configuration for REST mode
      - JWT_KEY_PATH=${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
      # Path for system binaries
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    networks:
      - datamonkey
    depends_on:
      - c2

  # Combined Slurm+service-datamonkey image is used for CLI mode
  # No sidecar container needed

  # Common Slurm service for both modes
  c2:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    build:
      context: ${SLURM_SERVICE_PATH:-../service-slurm}
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-21-08-6-1}
    entrypoint: [ "sh", "-c" ]
    command: [ "/usr/share/bin/slurm-interface.sh" ]
    hostname: c2
    container_name: c2
    privileged: true
    environment:
      SLURM_INTERFACE: ${SLURM_INTERFACE:-rest}
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      # Common volumes
      - user_data:/data/uploads
      - output_data:/data/output
      # Volume mounts - these will be used based on the mode
      # For REST mode, use named volumes
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      # JWT key for REST mode
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6818"
      - "9200"
      - "22"
    ports:
      - 9200:9200
      - ${SSH_PORT:-2222}:22
    networks:
      - datamonkey

  # The following services are only used in REST mode
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - datamonkey

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    build:
      context: ${SLURM_SERVICE_PATH:-../service-slurm}
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-21-08-6-1}
    command: [ "slurmdbd" ]
    container_name: slurmdbd
    hostname: slurmdbd
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - datamonkey

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    command: [ "slurmctld" ]
    container_name: slurmctld
    hostname: slurmctld
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - datamonkey

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    command: [ "slurmd" ]
    hostname: c1
    container_name: c1
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - user_data:/data/uploads
      - output_data:/data/output
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - datamonkey

networks:
  datamonkey:
    name: datamonkey
    driver: bridge
    
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  user_data:
  tracker_data:
  output_data:
