/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type HyPhyMethodsAPI struct {
}

// Post /api/v1/methods/busted/results
// Get a BUSTED job result 
func (api *HyPhyMethodsAPI) GetBUSTEDJob(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/methods/fel/results
// Get a FEL job result 
func (api *HyPhyMethodsAPI) GetFELJob(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/methods/busted
// Start and monitor a BUSTED job 
func (api *HyPhyMethodsAPI) StartBUSTEDJob(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/methods/fel
// Start and monitor a FEL job 
func (api *HyPhyMethodsAPI) StartFELJob(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

