/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type NrmRequest struct {

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// Save NRM+F model fit to a file
	SaveFit bool `json:"save_fit,omitempty"`
}
