/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type BgmRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	// Specify branches to test
	Branches string `json:"branches,omitempty"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// The type of data being analyzed
	DataType string `json:"data_type,omitempty"`

	// Number of MCMC steps to sample
	Steps int32 `json:"steps,omitempty"`

	// Number of MCMC steps to discard as burn-in
	BurnIn int32 `json:"burn_in,omitempty"`

	// Number of samples to extract from the chain
	Samples int32 `json:"samples,omitempty"`

	// Maximum number of parents allowed per node
	MaxParents int32 `json:"max_parents,omitempty"`

	// Minimum number of substitutions per site to include in the analysis
	MinSubs int32 `json:"min_subs,omitempty"`
}
