/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type FelRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	// Compute confidence intervals for estimated rates
	Ci string `json:"ci,omitempty"`

	// Include synonymous rate variation in the model
	Srv string `json:"srv,omitempty"`

	// Number of bootstrap resamples
	Resample float32 `json:"resample,omitempty"`

	// Specify handling of multiple nucleotide substitutions
	MultipleHits string `json:"multiple_hits,omitempty"`

	// Specify whether to estimate multiple hit rates for each site
	SiteMultihit string `json:"site_multihit,omitempty"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// Branches to include in the analysis. If empty, all branches are included.
	Branches []string `json:"branches,omitempty"`
}
