/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.1.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type BustedRequest struct {

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	// Include synonymous rate variation in the model
	Srv string `json:"srv,omitempty"`

	// Specify handling of multiple nucleotide substitutions
	MultipleHits string `json:"multiple_hits,omitempty"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// Branches to include in the analysis. If empty, all branches are included.
	Branches []string `json:"branches,omitempty"`

	// The number omega rate classes to include in the model
	Rates int32 `json:"rates,omitempty"`

	// The number synonymous rate classes to include in the model
	SynRates int32 `json:"syn_rates,omitempty"`

	// The number of points in the initial distributional guess for likelihood fitting
	GridSize int32 `json:"grid_size,omitempty"`

	// The number of initial random guesses to seed rate values optimization
	StartingPoints int32 `json:"starting_points,omitempty"`

	// An advanced experimental setting; include a rate class to capture misalignment artifacts
	ErrorSink string `json:"error_sink,omitempty"`
}
