/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.1.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type FubarRequest struct {

	// Path to the in-frame codon alignment file (e.g., .fasta, .nex)
	Alignment string `json:"alignment"`

	// Path to the phylogenetic tree file
	Tree string `json:"tree"`

	// Which genetic code should be used
	GeneticCode string `json:"genetic_code,omitempty"`

	// Number of grid points for the Bayesian analysis (must be between 5 and 50)
	GridPoints int32 `json:"grid_points,omitempty"`

	// Concentration parameter for the Dirichlet prior in the Bayesian estimation
	ConcentrationParameter float32 `json:"concentration_parameter,omitempty"`
}
