/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.1.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

// ChatMessage - A message in a chat session
type ChatMessage struct {

	// Role of the message sender
	Role string `json:"role"`

	// Content of the message
	Content string `json:"content"`

	// Timestamp when the message was sent (Unix timestamp in milliseconds)
	Timestamp int64 `json:"timestamp,omitempty"`
}
