/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

// MultihitRequest - Request parameters for MULTI-HIT analysis
type MultihitRequest struct {

	// Path to the alignment file (e.g., .fasta, .phy)
	AlignmentFile string `json:"alignment_file"`

	// The genetic code to use for the analysis
	GeneticCode string `json:"genetic_code"`

	// Toggle for accounting synonymous triple-hit substitutions
	TripleIslands bool `json:"triple_islands,omitempty"`

	// Number of rate classes to use
	RateClasses int32 `json:"rate_classes,omitempty"`
}
