/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type ServerError struct {

	// A general description of the error.
	Error string `json:"error,omitempty"`

	// A unique error code (if available).
	Code string `json:"code,omitempty"`

	// Optional details about the error.
	Details string `json:"details,omitempty"`
}
