/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.1.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type RelaxRequest struct {

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// Branches to be considered as 'Test'
	TestBranches []string `json:"test_branches,omitempty"`

	// Branches to be considered as 'Reference'
	ReferenceBranches []string `json:"reference_branches,omitempty"`

	// Type of analysis to run (All for descriptive models and RELAX test, Minimal for only the RELAX test)
	Models string `json:"models,omitempty"`

	// Number of omega rate classes
	Rates int32 `json:"rates,omitempty"`

	// Specify whether to handle zero-length branches
	KillZeroLengths string `json:"kill_zero_lengths,omitempty"`
}
