/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type HealthDetails struct {
	JobScheduler Status `json:"job_scheduler,omitempty"`

	Datamonkey Status `json:"datamonkey,omitempty"`

	Llm Status `json:"llm,omitempty"`

	Database Status `json:"database,omitempty"`
}
