/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type SlatkinRequest struct {

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	// The number of compartments/groups to test
	Groups int32 `json:"groups,omitempty"`

	// Array of compartment definitions
	CompartmentDefinitions []SlatkinRequestCompartmentDefinitionsInner `json:"compartment_definitions,omitempty"`

	// The number of bootstrap replicates
	Replicates int32 `json:"replicates,omitempty"`

	// Probability of branch selection for structured permutation [0-1]; 0 = classical Slatkin-Maddison, 1 = fully structured
	Weight float32 `json:"weight,omitempty"`

	// Whether to use bootstrap weights to respect well-supported clades
	UseBootstrap bool `json:"use_bootstrap,omitempty"`
}
