/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

// MultihitRequest - Request parameters for MULTI-HIT analysis
type MultihitRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment" validate:"regexp=^[a-zA-Z0-9]+$"`

	// The genetic code to use for the analysis
	GeneticCode string `json:"genetic_code"`

	// Toggle for accounting synonymous triple-hit substitutions
	TripleIslands string `json:"triple_islands,omitempty"`

	// Number of rate classes to use
	RateClasses int32 `json:"rate_classes,omitempty"`
}
