/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.1.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type MemeRequest struct {

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// Specify handling of multiple nucleotide substitutions
	MultipleHits string `json:"multiple_hits,omitempty"`

	// Specify whether to estimate multiple hit rates for each site
	SiteMultihit string `json:"site_multihit,omitempty"`

	// Number of different categories of non-synonymous rates
	Rates int32 `json:"rates,omitempty"`

	// Number of bootstrapping replicates
	Resample float32 `json:"resample,omitempty"`

	// Option to impute likely character states for missing data
	ImputeStates string `json:"impute_states,omitempty"`
}
