/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

// SlacRequest - Request parameters for SLAC (Single Likelihood Ancestor Counting) analysis
type SlacRequest struct {

	// Path to the alignment file (e.g., .fasta, .nex, .phy)
	AlignmentFile string `json:"alignment_file"`

	// The genetic code to use for the analysis
	GeneticCode string `json:"genetic_code"`

	// Specify branches to test
	Branches string `json:"branches,omitempty"`

	// Number of samples for ancestral reconstruction uncertainty
	Samples int32 `json:"samples,omitempty"`

	// Threshold for statistical significance
	Pvalue float32 `json:"pvalue,omitempty"`
}
