/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type ContrastFelRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree" validate:"regexp=^[a-zA-Z0-9]+$"`

	// Array of branch sets to be used for comparison (e.g., \"Source\" and \"Test\" groups)
	BranchSets []string `json:"branch_sets"`

	// Which genetic code should be used
	GeneticCode string `json:"genetic_code,omitempty"`

	// Include synonymous rate variation in the model (\"Yes\" or \"No\")
	Srv string `json:"srv,omitempty"`

	// Perform permutation significance tests (\"Yes\" or \"No\")
	Permutations string `json:"permutations,omitempty"`

	// Significance value for site tests
	PValue float32 `json:"p_value,omitempty"`

	// Significance value for False Discovery Rate reporting
	QValue float32 `json:"q_value,omitempty"`
}
