/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

// ChatConversation - A conversation between a user and the AI assistant
type ChatConversation struct {

	// Unique identifier for the conversation
	Id string `json:"id"`

	// Token identifying the user who owns this conversation
	UserToken string `json:"user_token"`

	// Optional title for the conversation
	Title string `json:"title,omitempty"`

	// Timestamp when the conversation was created (Unix timestamp in milliseconds)
	Created int64 `json:"created"`

	// Timestamp when the conversation was last updated (Unix timestamp in milliseconds)
	Updated int64 `json:"updated"`

	// List of messages in the conversation
	Messages []ChatMessage `json:"messages,omitempty"`
}
