/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type MethodsListMethodsInner struct {

	// Method identifier (e.g., \"fel\", \"busted\", \"absrel\")
	Id string `json:"id,omitempty"`

	// Human-readable name of the method
	Name string `json:"name,omitempty"`

	// Brief description of what the method does
	Description string `json:"description,omitempty"`

	// Current status of the method
	Status string `json:"status,omitempty"`

	// API endpoint to start a job for this method
	StartEndpoint string `json:"start_endpoint,omitempty"`

	// API endpoint to retrieve results for this method
	ResultEndpoint string `json:"result_endpoint,omitempty"`

	// List of parameters expected by this method
	Parameters []MethodsListMethodsInnerParametersInner `json:"parameters,omitempty"`
}
