/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.1.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type FadeRequest struct {

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	// Bayes Factor threshold for determining significant sites (default 100)
	BayesFactorThreshold int32 `json:"bayes_factor_threshold,omitempty"`
}
