/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"os"
)

type UploadRequest struct {

	Meta DatasetMeta `json:"meta,omitempty"`

	// Dataset File. incompatible with the url field
	File *os.File `json:"file,omitempty"`

	// URL of the file to upload. incompatible with the file field
	Url string `json:"url,omitempty"`
}
