/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type FubarRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree" validate:"regexp=^[a-zA-Z0-9]+$"`

	// Which genetic code should be used
	GeneticCode string `json:"genetic_code,omitempty"`

	// Number of grid points for the Bayesian analysis (must be between 5 and 50)
	GridPoints int32 `json:"grid_points,omitempty"`

	// Concentration parameter for the Dirichlet prior in the Bayesian estimation
	ConcentrationParameter float32 `json:"concentration_parameter,omitempty"`
}
