/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

// SlacRequest - Request parameters for SLAC (Single Likelihood Ancestor Counting) analysis
type SlacRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	Tree string `json:"tree,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// Branches to include in the analysis. If empty, all branches are included.
	Branches []string `json:"branches,omitempty"`

	// Number of samples for ancestral reconstruction uncertainty
	Samples int32 `json:"samples,omitempty"`

	// Threshold for statistical significance
	Pvalue float32 `json:"pvalue,omitempty"`
}
