/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

type GardRequest struct {

	// Token identifying the user who is starting the job
	UserToken string `json:"user_token,omitempty"`

	Alignment string `json:"alignment,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`

	GeneticCode GeneticCode `json:"genetic_code,omitempty"`

	// The type of data being analyzed
	DataType string `json:"data_type,omitempty"`

	// The optimization mode
	RunMode string `json:"run_mode,omitempty"`

	// Specifies the model for rate variation among sites
	SiteToSiteVariation string `json:"site_to_site_variation,omitempty"`

	// The number of discrete rate classes for rate variation
	RateClasses int32 `json:"rate_classes,omitempty"`

	// The substitution model to use
	Model string `json:"model,omitempty"`
}
