/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.0.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the BUSTEDAPI part of the API
	BUSTEDAPI BUSTEDAPI
	// Routes for the FELAPI part of the API
	FELAPI FELAPI
	// Routes for the FileUploadAndQCAPI part of the API
	FileUploadAndQCAPI FileUploadAndQCAPI
	// Routes for the HealthAPI part of the API
	HealthAPI HealthAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"GetBUSTEDJob",
			http.MethodPost,
			"/api/v1/methods/busted-result",
			handleFunctions.BUSTEDAPI.GetBUSTEDJob,
		},
		{
			"StartBUSTEDJob",
			http.MethodPost,
			"/api/v1/methods/busted-start",
			handleFunctions.BUSTEDAPI.StartBUSTEDJob,
		},
		{
			"GetFELJob",
			http.MethodPost,
			"/api/v1/methods/fel-result",
			handleFunctions.FELAPI.GetFELJob,
		},
		{
			"StartFELJob",
			http.MethodPost,
			"/api/v1/methods/fel-start",
			handleFunctions.FELAPI.StartFELJob,
		},
		{
			"GetDatasetsList",
			http.MethodGet,
			"/api/v1/datasets",
			handleFunctions.FileUploadAndQCAPI.GetDatasetsList,
		},
		{
			"PostDataset",
			http.MethodPost,
			"/api/v1/datasets",
			handleFunctions.FileUploadAndQCAPI.PostDataset,
		},
		{
			"GetHealth",
			http.MethodGet,
			"/api/v1/health",
			handleFunctions.HealthAPI.GetHealth,
		},
	}
}
