/*
 * Datamonkey API
 *
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * API version: 1.2.0
 * Contact: spond@temple.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datamonkey

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the ABSRELAPI part of the API
	ABSRELAPI ABSRELAPI
	// Routes for the BGMAPI part of the API
	BGMAPI BGMAPI
	// Routes for the BUSTEDAPI part of the API
	BUSTEDAPI BUSTEDAPI
	// Routes for the CONTRASTFELAPI part of the API
	CONTRASTFELAPI CONTRASTFELAPI
	// Routes for the ChatAPI part of the API
	ChatAPI ChatAPI
	// Routes for the FADEAPI part of the API
	FADEAPI FADEAPI
	// Routes for the FELAPI part of the API
	FELAPI FELAPI
	// Routes for the FUBARAPI part of the API
	FUBARAPI FUBARAPI
	// Routes for the FileUploadAndQCAPI part of the API
	FileUploadAndQCAPI FileUploadAndQCAPI
	// Routes for the GARDAPI part of the API
	GARDAPI GARDAPI
	// Routes for the HealthAPI part of the API
	HealthAPI HealthAPI
	// Routes for the JobsAPI part of the API
	JobsAPI JobsAPI
	// Routes for the MEMEAPI part of the API
	MEMEAPI MEMEAPI
	// Routes for the MULTIHITAPI part of the API
	MULTIHITAPI MULTIHITAPI
	// Routes for the MethodsAPI part of the API
	MethodsAPI MethodsAPI
	// Routes for the NRMAPI part of the API
	NRMAPI NRMAPI
	// Routes for the RELAXAPI part of the API
	RELAXAPI RELAXAPI
	// Routes for the SLACAPI part of the API
	SLACAPI SLACAPI
	// Routes for the SLATKINAPI part of the API
	SLATKINAPI SLATKINAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"GetABSRELJob",
			http.MethodPost,
			"/api/v1/methods/absrel-result",
			handleFunctions.ABSRELAPI.GetABSRELJob,
		},
		{
			"GetABSRELJobById",
			http.MethodGet,
			"/api/v1/methods/absrel-result",
			handleFunctions.ABSRELAPI.GetABSRELJobById,
		},
		{
			"StartABSRELJob",
			http.MethodPost,
			"/api/v1/methods/absrel-start",
			handleFunctions.ABSRELAPI.StartABSRELJob,
		},
		{
			"GetBGMJob",
			http.MethodPost,
			"/api/v1/methods/bgm-result",
			handleFunctions.BGMAPI.GetBGMJob,
		},
		{
			"GetBGMJobById",
			http.MethodGet,
			"/api/v1/methods/bgm-result",
			handleFunctions.BGMAPI.GetBGMJobById,
		},
		{
			"StartBGMJob",
			http.MethodPost,
			"/api/v1/methods/bgm-start",
			handleFunctions.BGMAPI.StartBGMJob,
		},
		{
			"GetBUSTEDJob",
			http.MethodPost,
			"/api/v1/methods/busted-result",
			handleFunctions.BUSTEDAPI.GetBUSTEDJob,
		},
		{
			"GetBUSTEDJobById",
			http.MethodGet,
			"/api/v1/methods/busted-result",
			handleFunctions.BUSTEDAPI.GetBUSTEDJobById,
		},
		{
			"StartBUSTEDJob",
			http.MethodPost,
			"/api/v1/methods/busted-start",
			handleFunctions.BUSTEDAPI.StartBUSTEDJob,
		},
		{
			"GetCONTRASTFELJob",
			http.MethodPost,
			"/api/v1/methods/contrast-fel-result",
			handleFunctions.CONTRASTFELAPI.GetCONTRASTFELJob,
		},
		{
			"GetContrastFELJobById",
			http.MethodGet,
			"/api/v1/methods/contrast-fel-result",
			handleFunctions.CONTRASTFELAPI.GetContrastFELJobById,
		},
		{
			"StartCONTRASTFELJob",
			http.MethodPost,
			"/api/v1/methods/contrast-fel-start",
			handleFunctions.CONTRASTFELAPI.StartCONTRASTFELJob,
		},
		{
			"CreateConversation",
			http.MethodPost,
			"/api/v1/chat",
			handleFunctions.ChatAPI.CreateConversation,
		},
		{
			"DeleteConversation",
			http.MethodDelete,
			"/api/v1/chat/:conversationId",
			handleFunctions.ChatAPI.DeleteConversation,
		},
		{
			"GetConversation",
			http.MethodGet,
			"/api/v1/chat/:conversationId",
			handleFunctions.ChatAPI.GetConversation,
		},
		{
			"GetConversationMessages",
			http.MethodGet,
			"/api/v1/chat/:conversationId/messages",
			handleFunctions.ChatAPI.GetConversationMessages,
		},
		{
			"ListUserConversations",
			http.MethodGet,
			"/api/v1/chat",
			handleFunctions.ChatAPI.ListUserConversations,
		},
		{
			"SendConversationMessage",
			http.MethodPost,
			"/api/v1/chat/:conversationId/messages",
			handleFunctions.ChatAPI.SendConversationMessage,
		},
		{
			"GetFadeResults",
			http.MethodPost,
			"/api/v1/methods/fade-result",
			handleFunctions.FADEAPI.GetFadeResults,
		},
		{
			"GetFadeResultsById",
			http.MethodGet,
			"/api/v1/methods/fade-result",
			handleFunctions.FADEAPI.GetFadeResultsById,
		},
		{
			"StartFadeJob",
			http.MethodPost,
			"/api/v1/methods/fade-start",
			handleFunctions.FADEAPI.StartFadeJob,
		},
		{
			"GetFELJob",
			http.MethodPost,
			"/api/v1/methods/fel-result",
			handleFunctions.FELAPI.GetFELJob,
		},
		{
			"GetFELJobById",
			http.MethodGet,
			"/api/v1/methods/fel-result",
			handleFunctions.FELAPI.GetFELJobById,
		},
		{
			"StartFELJob",
			http.MethodPost,
			"/api/v1/methods/fel-start",
			handleFunctions.FELAPI.StartFELJob,
		},
		{
			"GetFUBARJob",
			http.MethodPost,
			"/api/v1/methods/fubar-result",
			handleFunctions.FUBARAPI.GetFUBARJob,
		},
		{
			"GetFUBARJobById",
			http.MethodGet,
			"/api/v1/methods/fubar-result",
			handleFunctions.FUBARAPI.GetFUBARJobById,
		},
		{
			"StartFUBARJob",
			http.MethodPost,
			"/api/v1/methods/fubar-start",
			handleFunctions.FUBARAPI.StartFUBARJob,
		},
		{
			"GetDatasetById",
			http.MethodGet,
			"/api/v1/datasets/:datasetId",
			handleFunctions.FileUploadAndQCAPI.GetDatasetById,
		},
		{
			"GetDatasetsList",
			http.MethodGet,
			"/api/v1/datasets",
			handleFunctions.FileUploadAndQCAPI.GetDatasetsList,
		},
		{
			"PostDataset",
			http.MethodPost,
			"/api/v1/datasets",
			handleFunctions.FileUploadAndQCAPI.PostDataset,
		},
		{
			"GetGARDJob",
			http.MethodPost,
			"/api/v1/methods/gard-result",
			handleFunctions.GARDAPI.GetGARDJob,
		},
		{
			"GetGARDJobById",
			http.MethodGet,
			"/api/v1/methods/gard-result",
			handleFunctions.GARDAPI.GetGARDJobById,
		},
		{
			"StartGARDJob",
			http.MethodPost,
			"/api/v1/methods/gard-start",
			handleFunctions.GARDAPI.StartGARDJob,
		},
		{
			"GetHealth",
			http.MethodGet,
			"/api/v1/health",
			handleFunctions.HealthAPI.GetHealth,
		},
		{
			"GetJobsList",
			http.MethodGet,
			"/api/v1/jobs",
			handleFunctions.JobsAPI.GetJobsList,
		},
		{
			"GetMEMEJob",
			http.MethodPost,
			"/api/v1/methods/meme-result",
			handleFunctions.MEMEAPI.GetMEMEJob,
		},
		{
			"GetMEMEJobById",
			http.MethodGet,
			"/api/v1/methods/meme-result",
			handleFunctions.MEMEAPI.GetMEMEJobById,
		},
		{
			"StartMEMEJob",
			http.MethodPost,
			"/api/v1/methods/meme-start",
			handleFunctions.MEMEAPI.StartMEMEJob,
		},
		{
			"GetMULTIHITJob",
			http.MethodPost,
			"/api/v1/methods/multihit-result",
			handleFunctions.MULTIHITAPI.GetMULTIHITJob,
		},
		{
			"GetMULTIHITJobById",
			http.MethodGet,
			"/api/v1/methods/multihit-result",
			handleFunctions.MULTIHITAPI.GetMULTIHITJobById,
		},
		{
			"StartMULTIHITJob",
			http.MethodPost,
			"/api/v1/methods/multihit-start",
			handleFunctions.MULTIHITAPI.StartMULTIHITJob,
		},
		{
			"GetMethodsList",
			http.MethodGet,
			"/api/v1/methods",
			handleFunctions.MethodsAPI.GetMethodsList,
		},
		{
			"GetNRMJob",
			http.MethodPost,
			"/api/v1/methods/nrm-result",
			handleFunctions.NRMAPI.GetNRMJob,
		},
		{
			"GetNRMJobById",
			http.MethodGet,
			"/api/v1/methods/nrm-result",
			handleFunctions.NRMAPI.GetNRMJobById,
		},
		{
			"StartNRMJob",
			http.MethodPost,
			"/api/v1/methods/nrm-start",
			handleFunctions.NRMAPI.StartNRMJob,
		},
		{
			"GetRELAXJob",
			http.MethodPost,
			"/api/v1/methods/relax-result",
			handleFunctions.RELAXAPI.GetRELAXJob,
		},
		{
			"GetRELAXJobById",
			http.MethodGet,
			"/api/v1/methods/relax-result",
			handleFunctions.RELAXAPI.GetRELAXJobById,
		},
		{
			"StartRELAXJob",
			http.MethodPost,
			"/api/v1/methods/relax-start",
			handleFunctions.RELAXAPI.StartRELAXJob,
		},
		{
			"GetSLACJob",
			http.MethodPost,
			"/api/v1/methods/slac-result",
			handleFunctions.SLACAPI.GetSLACJob,
		},
		{
			"GetSLACJobById",
			http.MethodGet,
			"/api/v1/methods/slac-result",
			handleFunctions.SLACAPI.GetSLACJobById,
		},
		{
			"StartSLACJob",
			http.MethodPost,
			"/api/v1/methods/slac-start",
			handleFunctions.SLACAPI.StartSLACJob,
		},
		{
			"GetSlatkinResults",
			http.MethodPost,
			"/api/v1/methods/slatkin-result",
			handleFunctions.SLATKINAPI.GetSlatkinResults,
		},
		{
			"GetSlatkinResultsById",
			http.MethodGet,
			"/api/v1/methods/slatkin-result",
			handleFunctions.SLATKINAPI.GetSlatkinResultsById,
		},
		{
			"StartSlatkinJob",
			http.MethodPost,
			"/api/v1/methods/slatkin-start",
			handleFunctions.SLATKINAPI.StartSlatkinJob,
		},
	}
}
